- name: "Default Scan"
  parameters:
    target: "https://example.com"  # Will be dynamically replaced
    rules: 
      - "scan_rules/automatic"
    context: 
      name: "Default Context"
      includePaths:
        - "https://example.com/.*"  # Will be dynamically replaced
