- name: "Quick Scan"
  parameters:
    context: 
      name: "Default Context"
      url: "https://shopify.com"
    target:
      url: "https://shopify.com"
    rules:
      name: "Default Rule Set"
    policy:
      name: "Default Policy"
    spider:
      maxDuration: 10
    ajaxSpider:
      enabled: false
    activeScan:
      enabled: true
      policy: "Default Policy"
