- name: "Standard Vulnerability Scan"
  parameters:
    target: "https://example.com"  # REPLACE WITH YOUR TARGET DOMAIN
    context:
      name: "scan-context"
      urls:
        - "https://example.com*"   # REPLACE WITH YOUR DOMAIN PATTERN
  jobs:
    - name: spider
      type: spider
      parameters:
        maxDuration: 30  # Minutes
        
    - name: ajax-spider
      type: ajaxSpider
      parameters:
        maxDuration: 30  # Minutes
        
    - name: active-scan
      type: activeScan
      parameters:
        scanPolicyName: "Default Policy"
        strength: "MEDIUM"
        threshold: "MEDIUM"
