- name: Install scanning dependencies
        run: |
          # Enable command tracing for detailed debugging output
          set -x
          # Exit immediately if a command exits with a non-zero status
          set -e

          sudo apt-get update
          sudo apt-get install -y git python3 python3-pip nikto nmap unzip wget golang jq curl

          # Set Go environment variables
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> $GITHUB_ENV

          # Create Go bin directory if it doesn't exist, though go install usually does
          mkdir -p "$HOME/go/bin"

          echo "Installing Go tools..."
          go install github.com/tomnomnom/assetfinder@latest
          go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install github.com/lc/gau/v2/cmd/gau@latest
          go install github.com/projectdiscovery/katana/cmd/katana@latest
          go install github.com/sensepost/gowitness@latest # For web screenshots

          echo "Contents of Go bin directory before moving:"
          ls -l "$HOME/go/bin/" || true

          echo "Moving Go binaries to /usr/local/bin/"
          for tool in assetfinder nuclei httpx subfinder gau katana gowitness; do
            if [ -f "$HOME/go/bin/$tool" ]; then
              sudo mv "$HOME/go/bin/$tool" /usr/local/bin/
              echo "Moved $tool successfully."
            else
              echo "ERROR: Go tool '$tool' not found in $HOME/go/bin/. It might not have installed correctly."
              exit 1
            fi
          done

          # --- Attempt 1 (Preferred): Directly download 'main' branch ZIP ---
          echo "Attempting to download github-endpoints 'main' branch ZIP directly..."
          GITHUB_ENDPOINTS_DIRECT_ZIP_URL="https://github.com/initstring/github-endpoints/archive/refs/heads/main.zip"
          
          if wget --tries=5 --wait=5 "$GITHUB_ENDPOINTS_DIRECT_ZIP_URL" -O /tmp/github-endpoints-main.zip; then
            echo "Successfully downloaded github-endpoints 'main' branch ZIP."
            UNZIPPED_DIR=$(unzip -q -o /tmp/github-endpoints-main.zip -d /tmp/ | head -n 1 | awk -F'/' '{print $2}')
            
            if [ -z "$UNZIPPED_DIR" ]; then
              echo "ERROR: Failed to determine extracted directory name for github-endpoints ZIP."
              exit 1
            fi

            pip3 install "/tmp/$UNZIPPED_DIR" || { echo "ERROR: Failed to install github-endpoints from ZIP."; exit 1; }
            rm /tmp/github-endpoints-main.zip
            rm -rf "/tmp/$UNZIPPED_DIR"
            echo "github-endpoints installed successfully."
          else
            echo "WARNING: Direct ZIP download for github-endpoints failed. Falling back to Git clone."
            # --- Fallback Option 2: Clone the repository directly ---
            echo "Cloning github-endpoints repository..."
            GIT_REPO_DIR="/tmp/github-endpoints-repo"
            if git clone https://github.com/initstring/github-endpoints.git "$GIT_REPO_DIR"; then
              echo "Successfully cloned github-endpoints repository."
              pip3 install "$GIT_REPO_DIR" || { echo "ERROR: Failed to install github-endpoints from cloned repository."; exit 1; }
              rm -rf "$GIT_REPO_DIR"
              echo "github-endpoints installed successfully via Git clone."
            else
              echo "ERROR: Failed to clone github-endpoints repository. Cannot install."
              exit 1
            fi
          fi
          # --- END github-endpoints installation ---

          # Install Findomain
          echo "Installing Findomain..."
          curl -s https://api.github.com/repos/findomain/findomain/releases/latest \
            | grep "browser_download_url.*linux.zip" \
            | cut -d '"' -f 4 \
            | wget -i - || { echo "ERROR: Failed to download Findomain zip URL."; exit 1; }
          unzip findomain-linux.zip || { echo "ERROR: Failed to unzip Findomain."; exit 1; }
          chmod +x findomain
          sudo mv findomain /usr/local/bin/findomain || { echo "ERROR: Failed to move Findomain to /usr/local/bin."; exit 1; }
          echo "Findomain installed successfully."

          # Update Nuclei templates to the latest version
          echo "Updating Nuclei templates..."
          nuclei -update-templates -silent || { echo "WARNING: Nuclei template update failed."; }
          echo "Nuclei templates updated."
