name: Nuclei Vulnerability Scan

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
        HEAD
          go-version: '1.18.10'  # Match your local Go version  
          go-version: '1.18.10'  # Specify the Go version you want to use
         9d635c4f72640cafd8e1976e1de624fcb354a66b

      - name: Install Nuclei
        run: |
          go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest

      - name: Run Nuclei Vulnerability Scan
        run: |
          nuclei -u https://mtn.com -o nuclei-results.txt

      - name: Upload Nuclei Scan Results
        uses: actions/upload-artifact@v3  # Correct version
        with:
          name: nuclei-results
          path: nuclei-results.txt
