name: Bug Bounty Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install Nuclei
      run: |
        curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest | grep "browser_download_url.*linux_amd64.zip" | cut -d : -f 2,3 | tr -d \" | wget -i -
        unzip nuclei-linux_amd64.zip
        sudo mv nuclei /usr/local/bin/
        nuclei -version

    - name: Download Nuclei Templates
      run: |
        nuclei -update-templates
        nuclei -ut

    - name: Run Nuclei scan
      run: |
        nuclei -l urls.txt -t cves/ -o nuclei-results.txt

    - name: Upload Nuclei scan results
      uses: actions/upload-artifact@v3
      with:
        name: nuclei-scan-results
        path: nuclei-results.txt
