---
- name: Install Nuclei
  run: >
    # Download the latest release of Nuclei

    NUCLEI_URL=$(curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest \
      | grep "browser_download_url.*linux_amd64.zip" \
      | cut -d : -f 2,3 \
      | tr -d \" | tr -d '[:space:]') # Trim whitespace

    # Output the download URL for debugging

    echo "Nuclei download URL: $NUCLEI_URL"


    # Check if the URL is not empty

    if [[ -z "$NUCLEI_URL" ]]; then
      echo "Failed to get the download URL for Nuclei."
      exit 1
    fi


    # Download the zip file

    wget "$NUCLEI_URL" -O nuclei-linux_amd64.zip || { echo "Download failed"; exit 1; }


    # Unzip and move to local bin

    unzip nuclei-linux_amd64.zip || { echo "Unzip failed"; exit 1; }

    sudo mv nuclei /usr/local/bin/ || { echo "Move failed"; exit 1; }


    # Verify installation

    nuclei -version || { echo "Nuclei installation failed"; exit 1; }
