name: Benchmark HTTPX & Nuclei Throughput

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tools
        run: |
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          sudo mv ~/go/bin/* /usr/local/bin/
          nuclei -update-templates

      - name: Prepare Fast Targets
        run: |
          cat <<EOF > targets.txt
          https://example.com
          https://google.com
          https://github.com
          https://cloudflare.com
          https://openai.com
          https://wikipedia.org
          https://mozilla.org
          https://apple.com
          https://bing.com
          https://microsoft.com
          EOF

      - name: Benchmark HTTPX
        run: |
          echo "Running HTTPX benchmark..."
          start=$(date +%s)
          httpx -list targets.txt -silent -threads 50 -no-color > /dev/null
          end=$(date +%s)
          duration=$((end - start))
          total=$(wc -l < targets.txt)
          rpm=$(( (total * 60) / duration ))
          echo "HTTPX completed in $duration seconds"
          echo "HTTPX estimated throughput: $rpm requests/minute"

      - name: Benchmark Nuclei
        run: |
          echo "Running Nuclei benchmark..."
          start=$(date +%s)
          nuclei -list targets.txt \
            -t cves/ \
            -severity low,medium \
            -rate-limit 200 \
            -silent \
            -timeout 10 \
            -j > /dev/null
          end=$(date +%s)
          duration=$((end - start))
          total=$(wc -l < targets.txt)
          rpm=$(( (total * 60) / duration ))
          echo "Nuclei completed in $duration seconds"
          echo "Nuclei estimated throughput: $rpm requests/minute"
