name: Advanced Vulnerability Scan Suite

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '*.md'
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM
  workflow_dispatch:

env:
  NUCLEI_TEMPLATES_DIR: /tmp/nuclei-templates
  MAX_SCAN_TIME: 7200

jobs:
  reconnaissance:
    runs-on: ubuntu-latest
    outputs:
      target_count: ${{ steps.targets.outputs.count }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Recon Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3-pip
          pip install --upgrade pip
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/tomnomnom/assetfinder@latest
          go install github.com/lc/gau/v2/cmd/gau@latest
          sudo mv ~/go/bin/* /usr/local/bin/

      - name: Run Comprehensive Discovery
        id: targets
        run: |
          mkdir -p targets
          cat .github/workflows/domains.txt | while read -r domain; do
            subfinder -d "$domain" -silent | httpx -silent -status-code -title -tech-detect -json -o "targets/${domain//./_}.json"
            gau "$domain" --subs | httpx -silent >> "targets/${domain//./_}.txt"
          done
          echo "count=$(find targets -type f -name "*.json" | wc -l)" >> $GITHUB_OUTPUT

  prepare-targets:
    needs: reconnaissance
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.get-targets.outputs.targets }}
    steps:
      - uses: actions/checkout@v4

      - name: Restore Recon Data
        run: mkdir -p targets && cp -r targets/* targets/ || true

      - name: Get Scan Targets
        id: get-targets
        run: |
          targets=$(jq -r '.url' targets/*.json | tr '\n' ',' | sed 's/,$//')
          echo "targets=[$targets]" >> $GITHUB_OUTPUT

  split-targets:
    needs: prepare-targets
    runs-on: ubuntu-latest
    outputs:
      shards: ${{ steps.shard.outputs.shards }}
    steps:
      - uses: actions/checkout@v4

      - name: Load Targets
        run: mkdir -p targets && cp -r targets/* targets/ || true

      - name: Split Targets into Chunks
        id: shard
        run: |
          mkdir split
          shard_size=5
          count=0
          index=0
          for url in $(jq -r '.url' targets/*.json); do
            echo "$url" >> split/chunk_$index.txt
            count=$((count+1))
            if [ "$count" -eq "$shard_size" ]; then
              index=$((index+1))
              count=0
            fi
          done

          files=$(ls split/chunk_*.txt | jq -R -s -c 'split("\n")[:-1]')
          echo "shards=$files" >> $GITHUB_OUTPUT

      - name: Upload Shards
        uses: actions/upload-artifact@v3
        with:
          name: target-shards
          path: split/

  scanning:
    needs: split-targets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: ${{ fromJson(needs.split-targets.outputs.shards) }}
      max-parallel: 4
    steps:
      - uses: actions/checkout@v4

      - name: Download Target Shard
        uses: actions/download-artifact@v3
        with:
          name: target-shards
          path: shards/

      - name: Install Tools
        run: |
          go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          nuclei -update-templates
          sudo mv ~/go/bin/nuclei /usr/local/bin/

      - name: Run Nuclei on Shard
        run: |
          mkdir -p scan_results
          input_file="shards/${{ matrix.shard }}"
          nuclei -l "$input_file" \
            -t ~/nuclei-templates/ \
            -severity high,critical \
            -rate-limit 200 \
            -timeout 15 \
            -j -silent -o "scan_results/nuclei_${{ matrix.shard }}.json"

      - name: Upload Scan Result
        uses: actions/upload-artifact@v3
        with:
          name: nuclei-results-${{ matrix.shard }}
          path: scan_results/

  post_processing:
    needs: scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download All Results
        uses: actions/download-artifact@v3
        with:
          path: scan_results

      - name: Generate Consolidated Report
        run: |
          mkdir -p reports
          jq -s 'flatten' scan_results/**/*.json > reports/combined_results.json

          echo "# Security Scan Report" > reports/executive_summary.md
          echo "Generated: $(date)" >> reports/executive_summary.md
          echo "## Findings Overview" >> reports/executive_summary.md
          echo "Total Vulnerabilities: $(jq 'length' reports/combined_results.json)" >> reports/executive_summary.md
          echo "Critical: $(jq '[.[] | select(.info.severity == "critical")] | length' reports/combined_results.json)" >> reports/executive_summary.md
          echo "High: $(jq '[.[] | select(.info.severity == "high")] | length' reports/combined_results.json)" >> reports/executive_summary.md

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: reports/

  notification:
    needs: post_processing
    runs-on: ubuntu-latest
    steps:
      - name: Download Report
        uses: actions/download-artifact@v3
        with:
          name: security-reports
          path: reports/

      - name: Send Smart Notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          critical=$(jq '[.[] | select(.info.severity == "critical")] | length' reports/combined_results.json)
          high=$(jq '[.[] | select(.info.severity == "high")] | length' reports/combined_results.json)

          if [ "$critical" -gt 0 ]; then
            color="#ff0000"
            priority="URGENT"
            icon=":fire:"
          elif [ "$high" -gt 0 ]; then
            color="#ff9900"
            priority="High"
            icon=":warning:"
          else
            color="#36a64f"
            priority="Normal"
            icon=":white_check_mark:"
          fi

          payload=$(jq -n \
            --arg text "$icon Security Scan Completed ($priority)" \
            --arg color "$color" \
            --arg critical "$critical" \
            --arg high "$high" \
            --arg run_url "https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
            '{
              "attachments": [
                {
                  "color": $color,
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*\($text)*"
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Critical Findings*\n\($critical)"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*High Findings*\n\($high)"
                        }
                      ]
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "View Full Report"
                          },
                          "url": $run_url
                        }
                      ]
                    }
                  ]
                }
              ]
            }')

          curl -X POST $SLACK_WEBHOOK \
            -H "Content-type: application/json" \
            --data "$payload"
