name: Bug Bounty Recon Advanced

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily at midnight

jobs:
  recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install Tools
      run: |
        sudo apt update && sudo apt install -y nmap git curl jq python3-pip cargo
        go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
        go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
        go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
        go install -v github.com/hakluke/hakrawler@latest
        go install github.com/tomnomnom/gau@latest
        go install github.com/tomnomnom/assetfinder@latest
        go install github.com/lc/gau@latest
        go install github.com/lc/subjs@latest
        pip install git+https://github.com/owasp-amass/amass.git
        cargo install findomain

    - name: Run Recon Script
      run: |
        mkdir recon_output
        DOMAINS_FILE="domains.txt"
        mkdir -p results

        while IFS= read -r domain; do
          echo "[+] Enumerating subdomains for $domain"

          subfinder -d $domain -silent > results/$domain.subs.txt
          findomain -t $domain -q >> results/$domain.subs.txt
          amass enum -passive -d $domain >> results/$domain.subs.txt

          sort -u results/$domain.subs.txt -o results/$domain.subs.txt

          echo "[+] Checking live hosts for $domain"
          httpx -l results/$domain.subs.txt -silent -title -status-code -tech-detect > results/$domain.live.txt

          echo "[+] Port scanning for $domain"
          naabu -l results/$domain.subs.txt -silent > results/$domain.ports.txt

          echo "[+] Crawling and URL fetching for $domain"
          cat results/$domain.live.txt | cut -d ' ' -f1 | hakrawler > results/$domain.hakrawler.txt
          gau $domain > results/$domain.gau.txt

          echo "[+] Running nuclei on $domain"
          nuclei -l results/$domain.live.txt -severity critical,high,medium -c 50 -silent -o results/$domain.nuclei.txt

        done < "$DOMAINS_FILE"

        echo "[+] Global diff check"
        if [ -f old_subs.txt ]; then
          comm -13 <(sort old_subs.txt) <(cat results/*.subs.txt | sort -u) > results/new_subdomains.txt
        fi
        cat results/*.subs.txt | sort -u > old_subs.txt

    - name: Send Slack Notification
      if: always()
      run: |
        curl -X POST -H 'Content-type: application/json' \
          --data "{\n            \"text\": \"Recon Complete ✅ - Check findings in the GitHub Action artifacts.\"\n          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: recon-results
        path: results
