name: Vulnerability Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manual trigger

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to use Node.js v16/v20 compatible version

      # OWASP ZAP Scan using the latest GitHub Action version
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0 # Update to a newer version compatible with Node.js 16 or 20
        with:
          target: 'https://mtn.com'
          rules_file_name: '.github/zap/rules.tsv'  # Optional: If you want to define custom rules
          report: true
        continue-on-error: true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: zap-report
          path: zap_scan.html # Ensure this matches the output from ZAP

      # Nikto Scan using installation via APT
      - name: Install Nikto
        run: sudo apt-get update && sudo apt-get install -y nikto

      - name: Run Nikto Scan
        run: |
          mkdir -p nikto-output
          nikto -h https://mtn.com -output nikto-output/nikto_report.txt
        continue-on-error: true

      - name: Upload Nikto report
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: nikto-report
          path: nikto-output/nikto_report.txt

      - name: Display Scan Summary
        run: |
          echo "OWASP ZAP and Nikto Scans Completed"
