name: Vulnerability Scanning & Change Monitoring

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  monitor-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use Subfinder or Sublist3r to detect subdomains
      - name: Install Subfinder
        run: sudo apt-get install -y subfinder

      - name: Find subdomains
        run: |
          subfinder -d mtn.com -silent > subdomains.txt

      # Check for new subdomains by comparing with the last run
      - name: Compare Subdomains
        run: |
          if [ -f old_subdomains.txt ]; then
            diff subdomains.txt old_subdomains.txt || echo "New subdomains detected"
          else
            echo "First run, no old subdomains to compare."
          fi
          cp subdomains.txt old_subdomains.txt  # Save current subdomains for the next run

      # Run OWASP ZAP & Nikto if changes detected
      - name: Run OWASP ZAP Scan
        if: steps.compare_subdomains.outputs.changed == 'true'  # Run ZAP only if new subdomains detected
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://mtn.com'
          rules_file_name: '.github/zap/rules.tsv'
        continue-on-error: true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: owasp-zap-report.html

      - name: Install Nikto
        run: sudo apt-get update && sudo apt-get install -y nikto

      - name: Run Nikto Scan
        run: |
          mkdir -p nikto-output
          nikto -h https://mtn.com -output nikto-output/nikto_report.txt
        continue-on-error: true

      - name: Upload Nikto report
        uses: actions/upload-artifact@v4
        with:
          name: nikto-report
          path: nikto-output/nikto_report.txt

      - name: Display Scan Summary
        run: |
          echo "OWASP ZAP and Nikto Scans Completed"
